/** Canonical site identity used by SEO.svelte and anything that overrides it. */
export const SITE_NAME = 'davis9001.dev';
export const SITE_URL = 'https://davis9001.dev';

/**
 * Default Open Graph / Twitter card image.
 *
 * The file is regenerated by `bun run screenshot:og-cover` from the hidden
 * `/hidden/og-cover` route. Bump `?v=` whenever the artwork changes — Discord,
 * Slack and X cache unfurled images by URL, so a same-URL replacement can keep
 * showing the old card for weeks.
 */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/cover.png?v=2`;
