/**
 * Blog import transforms — pure helpers used by
 * scripts/generate-blog-migration.ts to turn the markdown blog into an
 * idempotent SQL migration seeding the CMS blog content type.
 */

export const BLOG_TYPE_ID = 'ct-blog-system';

export interface ImportPost {
	slug: string;
	title: string;
	publishedAt: string;
	summary: string;
	tags: string[];
	bodyHtml: string;
	readTime: number;
}

/** Single-quote a string for SQLite, doubling embedded quotes */
export function sqlQuote(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

/** Cap an excerpt at the blog field's 300-char validation limit */
export function truncateExcerpt(summary: string, max = 300): string {
	const clean = (summary || '').trim();
	if (clean.length <= max) {
		return clean;
	}
	return clean.slice(0, max - 1).trimEnd() + '…';
}

/** Deterministic ids so re-running the generator never re-imports */
export function importItemId(slug: string): string {
	return `import-blog-${slug}`;
}

export function importTagId(tagSlug: string): string {
	return `import-tag-${tagSlug}`;
}

export function tagSlug(tag: string): string {
	return tag
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');
}

/** The fields JSON stored on an imported item */
export function postFieldsJson(post: ImportPost): string {
	return JSON.stringify({
		excerpt: truncateExcerpt(post.summary),
		body: post.bodyHtml,
		featured_image: '',
		category: 'update',
		read_time: post.readTime
	});
}

/** INSERT for one post — no-op when a blog item with that slug exists */
export function buildItemInsert(post: ImportPost): string {
	return `INSERT INTO content_items (id, content_type_id, slug, title, status, fields, seo_title, seo_description, seo_image, author_id, published_at, created_at, updated_at)
SELECT ${sqlQuote(importItemId(post.slug))}, ct.id, ${sqlQuote(post.slug)}, ${sqlQuote(post.title)}, 'published', ${sqlQuote(postFieldsJson(post))}, NULL, ${sqlQuote(truncateExcerpt(post.summary))}, NULL, NULL, ${sqlQuote(post.publishedAt)}, ${sqlQuote(post.publishedAt)}, ${sqlQuote(post.publishedAt)}
FROM content_types ct
WHERE ct.slug = 'blog'
	AND NOT EXISTS (
		SELECT 1 FROM content_items ci WHERE ci.content_type_id = ct.id AND ci.slug = ${sqlQuote(post.slug)}
	);`;
}

/** INSERTs for a post's tags and item-tag junctions (all idempotent) */
export function buildTagInserts(post: ImportPost): string[] {
	const statements: string[] = [];
	for (const tag of post.tags) {
		const slug = tagSlug(tag);
		if (!slug) continue;

		statements.push(`INSERT INTO content_tags (id, content_type_id, name, slug)
SELECT ${sqlQuote(importTagId(slug))}, ct.id, ${sqlQuote(tag)}, ${sqlQuote(slug)}
FROM content_types ct
WHERE ct.slug = 'blog'
	AND NOT EXISTS (
		SELECT 1 FROM content_tags t WHERE t.content_type_id = ct.id AND t.slug = ${sqlQuote(slug)}
	);`);

		statements.push(`INSERT OR IGNORE INTO content_item_tags (content_item_id, content_tag_id)
SELECT ci.id, t.id
FROM content_items ci
JOIN content_types ct ON ct.id = ci.content_type_id
JOIN content_tags t ON t.content_type_id = ct.id
WHERE ct.slug = 'blog' AND ci.slug = ${sqlQuote(post.slug)} AND t.slug = ${sqlQuote(slug)};`);
	}
	return statements;
}

/** The content type seed — adopted by syncContentTypes when code deploys */
export function buildTypeSeed(fieldsJson: string, settingsJson: string): string {
	return `INSERT INTO content_types (id, slug, name, description, fields, settings, icon, sort_order, is_system)
SELECT ${sqlQuote(BLOG_TYPE_ID)}, 'blog', 'Blog Posts', 'Blog articles, news, and updates', ${sqlQuote(fieldsJson)}, ${sqlQuote(settingsJson)}, 'article', 0, 1
WHERE NOT EXISTS (SELECT 1 FROM content_types WHERE slug = 'blog');`;
}

/** Assemble the full migration file */
export function buildBlogMigrationSql(
	posts: ImportPost[],
	fieldsJson: string,
	settingsJson: string
): string {
	const parts: string[] = [
		'-- Migration: import the markdown blog into the CMS',
		'-- Generated by scripts/generate-blog-migration.ts — do not edit after applying.',
		'-- Idempotent: every statement no-ops when its row already exists.',
		'',
		buildTypeSeed(fieldsJson, settingsJson),
		''
	];

	for (const post of posts) {
		parts.push(`-- ${post.slug}`);
		parts.push(buildItemInsert(post));
		parts.push(...buildTagInserts(post));
		parts.push('');
	}

	return parts.join('\n');
}
