/**
 * TipTap atom node for block markup the editor's schema cannot model.
 *
 * ProseMirror does not merely drop what its schema has no node for — it parses
 * the children as prose and writes the flattened result back on save, so the
 * save reports success and the post keeps a plausible length. That is what
 * destroyed both chart figures in taking-on-client-websites-again on
 * 2026-08-08; they were wrong in public for five days.
 *
 * Three shapes are affected, all allowed by src/lib/cms/sanitize.ts and none
 * modelled by StarterKit:
 *
 *   <svg …>…</svg>            charts and illustrations → labels become prose
 *   <figure>…</figure>        wrapper dropped; a <figcaption> becomes a <p>
 *   <table>…</table>          the entire table collapses to one paragraph
 *
 * Each is captured as an atom holding its outerHTML verbatim and rendered
 * straight back, so a load/save round-trip is lossless. In the editor the node
 * shows the real markup behind a dashed outline; it is not editable in the
 * WYSIWYG, and the HTML source button is how you change it. That is an
 * acceptable trade for content that is authored by hand and generated by
 * scripts/charts/build.mjs — and strictly better than the alternative, which
 * is losing it.
 *
 * Captured HTML passes through sanitizeHtml on the way in, the same filter the
 * write path applies, so the stored form is already a fixed point and nothing
 * can enter the document that the write path would have rejected.
 *
 * src/lib/cms/content-loss.ts is the net underneath this: it refuses any save
 * that reduces the count of these elements, which covers the cases nobody has
 * thought of yet.
 */

import { Node } from '@tiptap/core';
import type { DOMOutputSpec } from 'prosemirror-model';
import { sanitizeHtml } from './sanitize';

/** Tags preserved verbatim. Every one of these is destroyed without this node. */
export const PRESERVED_TAGS = ['figure', 'table', 'svg'] as const;

/** Build a detached element from stored HTML. Returns null when it won't parse. */
export function elementFromHtml(html: string): HTMLElement | null {
	if (typeof document === 'undefined' || typeof html !== 'string' || !html.trim()) {
		return null;
	}
	const template = document.createElement('template');
	template.innerHTML = html.trim();
	return (template.content.firstElementChild as HTMLElement) ?? null;
}

export const PreservedBlock = Node.create({
	name: 'preservedBlock',
	group: 'block',
	atom: true,
	draggable: true,
	selectable: true,

	addAttributes() {
		return {
			html: {
				default: '',
				parseHTML: (element: HTMLElement) => sanitizeHtml(element.outerHTML),
				// The markup lives in the node's own output, never as an attribute.
				renderHTML: () => ({})
			}
		};
	},

	parseHTML() {
		// figure before svg so a chart figure is captured as one unit — the
		// wrapper survives and the inner svg is not matched separately.
		return PRESERVED_TAGS.map((tag) => ({ tag, priority: 60 }));
	},

	renderHTML({ node }) {
		const element = elementFromHtml(String(node.attrs.html ?? ''));
		if (element) {
			return element as unknown as DOMOutputSpec;
		}
		// Only reachable with no document (SSR) or unparseable stored HTML. An
		// empty marker is preferable to throwing mid-serialize and losing the body.
		return ['div', { 'data-preserved-block': '' }] as DOMOutputSpec;
	},

	addNodeView() {
		return ({ node }) => {
			const dom = document.createElement('div');
			dom.className = 'rte-preserved-block';
			dom.contentEditable = 'false';
			const element = elementFromHtml(String(node.attrs.html ?? ''));
			if (element) {
				dom.appendChild(element);
			} else {
				dom.textContent = 'Preserved markup';
			}
			return { dom };
		};
	}
});
