/**
 * Tests for the blog import transforms ($lib/cms/blog-import)
 */
import { describe, expect, it } from 'vitest';

import {
	buildBlogMigrationSql,
	buildItemInsert,
	buildTagInserts,
	buildTypeSeed,
	importItemId,
	importTagId,
	postFieldsJson,
	sqlQuote,
	tagSlug,
	truncateExcerpt,
	type ImportPost
} from '../../src/lib/cms/blog-import';

function makePost(overrides: Partial<ImportPost> = {}): ImportPost {
	return {
		slug: 'hello-world',
		title: "Hello 'World'",
		publishedAt: '2026-01-01T00:00:00Z',
		summary: 'A summary',
		tags: ['Linux', 'Quantum Mechanics'],
		bodyHtml: `<p>It's <strong>great</strong></p>`,
		readTime: 3,
		...overrides
	};
}

describe('sqlQuote', () => {
	it('doubles single quotes', () => {
		expect(sqlQuote("it's")).toBe("'it''s'");
		expect(sqlQuote('plain')).toBe("'plain'");
	});
});

describe('truncateExcerpt', () => {
	it('passes short summaries through', () => {
		expect(truncateExcerpt('short')).toBe('short');
	});

	it('caps at 300 chars with an ellipsis', () => {
		const long = 'x'.repeat(400);
		const result = truncateExcerpt(long);
		expect(result.length).toBeLessThanOrEqual(300);
		expect(result.endsWith('…')).toBe(true);
	});

	it('handles empty input', () => {
		expect(truncateExcerpt('')).toBe('');
		expect(truncateExcerpt(undefined as unknown as string)).toBe('');
	});
});

describe('ids and slugs', () => {
	it('builds deterministic ids', () => {
		expect(importItemId('a-post')).toBe('import-blog-a-post');
		expect(importTagId('linux')).toBe('import-tag-linux');
	});

	it('slugifies tags', () => {
		expect(tagSlug('Quantum Mechanics')).toBe('quantum-mechanics');
		expect(tagSlug('  C++ ')).toBe('c');
	});
});

describe('buildItemInsert', () => {
	it('produces an idempotent insert with escaped content', () => {
		const sql = buildItemInsert(makePost());
		expect(sql).toContain("WHERE ct.slug = 'blog'");
		expect(sql).toContain('NOT EXISTS');
		expect(sql).toContain("'import-blog-hello-world'");
		expect(sql).toContain("'Hello ''World'''");
		// fields JSON with quotes escaped
		expect(sql).toContain("It''s");
		expect(sql).toContain("'published'");
	});

	it('stores excerpt/body/read_time in the fields JSON', () => {
		const fields = JSON.parse(postFieldsJson(makePost()));
		expect(fields.excerpt).toBe('A summary');
		expect(fields.body).toContain('<strong>');
		expect(fields.read_time).toBe(3);
		expect(fields.category).toBe('update');
	});
});

describe('buildTagInserts', () => {
	it('creates a tag insert and junction per tag', () => {
		const statements = buildTagInserts(makePost());
		expect(statements).toHaveLength(4);
		expect(statements[0]).toContain("'import-tag-linux'");
		expect(statements[1]).toContain('INSERT OR IGNORE INTO content_item_tags');
		expect(statements[2]).toContain("'quantum-mechanics'");
	});

	it('skips tags that slugify to nothing', () => {
		expect(buildTagInserts(makePost({ tags: ['---'] }))).toHaveLength(0);
	});
});

describe('buildBlogMigrationSql', () => {
	it('assembles seed + posts with the generated header', () => {
		const sql = buildBlogMigrationSql([makePost()], '[]', '{}');
		expect(sql).toContain('-- Generated by scripts/generate-blog-migration.ts');
		expect(sql).toContain("'ct-blog-system'");
		expect(sql).toContain('-- hello-world');
		expect(sql.indexOf('content_types')).toBeLessThan(sql.indexOf('content_items'));
	});

	it('type seed no-ops when blog type exists', () => {
		expect(buildTypeSeed('[]', '{}')).toContain(
			"WHERE NOT EXISTS (SELECT 1 FROM content_types WHERE slug = 'blog')"
		);
	});
});
